In [1]:
import pandas as pd
from sklearn.feature_extraction import DictVectorizer
import numpy as np

In [2]:
with open(r"C:\Temp\thesis_data\fromPaper\promoter\promoters.data") as f:
    content = f.readlines()

In [3]:
features_for_df = {}

In [4]:
target = [1 if s[0]=='+' else 0 for s in content ]
features_for_df['target'] = target

In [5]:
last = [s.split(',')[-1].strip() for s in content]
number_of_features = len(last[0])
for i in range(number_of_features):
    features_for_df[str(i)] = [l[i] for l in last]

In [6]:
df = pd.DataFrame.from_dict(features_for_df)
df.head()

0  1 10 11 12 13 14 15 16 17  ...   52 53 54 55 56  6  7  8  9 target
0  t  a  a  c  g  c  t  t  g  c  ...    g  t  c  g  t  c  a  a  t      1
1  t  g  a  c  a  g  t  t  g  t  ...    g  c  c  a  a  c  c  t  g      1
2  g  t  a  c  t  a  g  t  g  c  ...    c  g  g  c  g  g  a  g  a      1
3  a  a  t  g  t  a  t  c  g  a  ...    a  a  c  t  c  g  a  t  g      1
4  t  c  a  c  t  a  t  t  g  a  ...    g  g  t  a  g  a  t  t  a      1

[5 rows x 58 columns]

In [7]:
print df.shape

(106, 58)


In [8]:
def encode_onehot(df, cols):
    vec = DictVectorizer()

    vec_data = pd.DataFrame(vec.fit_transform(df[cols].to_dict(outtype='records')).toarray())
    vec_data.columns = vec.get_feature_names()
    vec_data.index = df.index

    df = df.drop(cols, axis=1)
    df = df.join(vec_data)
    return df

In [9]:
df = encode_onehot(df, [str(i) for i in range(number_of_features)])

C:\Users\tomjur\AppData\Local\Continuum\Anaconda2\lib\site-packages\ipykernel\__main__.py:4: FutureWarning: the 'outtype' keyword is deprecated, use 'orient' instead


In [10]:
df.shape

(106, 229)

In [11]:
target = df.target.values
target

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int64)

In [12]:
target.sum() / float(target.shape[0])

0.5

In [13]:
data = df.drop('target',axis=1).values
data.shape

(106L, 228L)

In [14]:
from sklearn import tree
from sklearn.model_selection import cross_val_score
for d in [1,3,5,10]:
    tree_classifier = tree.DecisionTreeClassifier(max_depth=d)
    scores = cross_val_score(tree_classifier, data, target, cv=5)
    print d
    print scores
    print scores.mean()
    print

1
[ 0.77272727  0.72727273  0.77272727  0.7         0.7       ]
0.734545454545

3
[ 0.81818182  0.77272727  0.77272727  0.7         0.55      ]
0.722727272727

5
[ 0.72727273  0.63636364  0.90909091  0.75        0.6       ]
0.724545454545

10
[ 0.72727273  0.68181818  0.77272727  0.75        0.75      ]
0.736363636364



In [15]:
from TreeClassifier import *
from sklearn.model_selection import cross_val_score
for normalize_mode in ['norm', 'dropSize', 'no']:
    for d in [1,3,5,10]:
        tree_classifier = TreeClassifier(0.001, d, normalizer_mode=normalize_mode, fit_full_tree=True, print_debug=False)
        scores = cross_val_score(tree_classifier, data, target, cv=5)
        print d
        print scores
        print scores.mean()
        print

full normalization
full normalization
full normalization
full normalization
full normalization
1
[ 0.5  0.5  0.5  0.5  0.5]
0.5

full normalization
full normalization
full normalization
full normalization
full normalization
3
[ 0.90909091  0.86363636  0.95454545  1.          0.85      ]
0.915454545455

full normalization
full normalization
full normalization
full normalization
full normalization
5
[ 0.90909091  0.86363636  0.90909091  1.          0.85      ]
0.906363636364

full normalization
full normalization
full normalization
full normalization
full normalization
10
[ 0.90909091  0.86363636  0.90909091  1.          0.85      ]
0.906363636364

drop size feature
drop size feature
drop size feature
drop size feature
drop size feature
1
[ 0.5  0.5  0.5  0.5  0.5]
0.5

drop size feature
drop size feature
drop size feature
drop size feature
drop size feature
3
[ 0.90909091  0.86363636  0.95454545  1.          0.85      ]
0.915454545455

drop size feature
drop size feature
drop size featu

In [16]:
from TreeClassifierWithBias import *
from sklearn.model_selection import cross_val_score
for normalize_mode in [True, False]:
    for d in [1,3,5,10]:
        tree_classifier = TreeClassifierWithBias(0.001, d, normalize_to_one=normalize_mode , fit_full_tree=True, print_debug=False)
        scores = cross_val_score(tree_classifier, data, target, cv=5)
        print d
        print scores
        print scores.mean()
        print

1
[ 0.5  0.5  0.5  0.5  0.5]
0.5

3
[ 0.90909091  0.72727273  0.95454545  0.8         0.8       ]
0.838181818182

5
[ 0.90909091  0.77272727  0.95454545  0.8         0.8       ]
0.847272727273

10
[ 0.90909091  0.77272727  0.95454545  0.8         0.8       ]
0.847272727273

1
[ 0.5  0.5  0.5  0.5  0.5]
0.5



AttributeError: 'NoneType' object has no attribute 'get_probabilities'

In [ ]:
from sklearn.svm import LinearSVC
from sklearn.model_selection import cross_val_score

svm_classifier = LinearSVC()
scores = cross_val_score(svm_classifier, data, target, cv=5)
print scores
print scores.mean()
print